In [9]:
import numpy as np
import pandas as pd

def normalize(image):
    maximum = image.max()
    minimum = image.min()
    
    for x in range(len(image)):
        for y in range(len(image[0])):
            p = image[x,y]
            image[x,y] = (float(p - minimum) * 255.0)/float(maximum-minimum)
    
    return image


print(normalize(np.array([[2.0,2.0], [3.0,2.0]])))


[[  0.   0.]
 [255.   0.]]


In [242]:
import json
import numpy
import pandas as pd
    
def weigh_pokemons(filename, weight):
  
    out = []

    with open(filename) as f:
        data = json.load(f)
        for pkmn in data["pokemon"]:
            if (float(pkmn["weight"].split(" ")[0]) == weight):
                out.append(pkmn["name"])
        
    return out
    
weigh_pokemons("pokedex.json", 100)

['Venusaur']

In [46]:
import numpy as np
import pandas as pd
import math

def reflections_and_projections(points):
    
    arrYOne = np.matmul(points,[[1, 0], [0, -1]]) 
    arrPi = np.matmul(arrYOne, [[0, -1], [1, 0]])
    arrLine = np.matmul(arrPi, [[1, 3], [3, 9]])
    arrLine = arrLine*.1
    
    return arrLine
    
    # Formula to rotate across y 
    #
    #
    #
print(reflections_and_projections(np.array([[2.0,2.0], [3.0,2.0]])))
    
    
    
    
    
    
    
    

[[2. 2.]
 [3. 2.]]
[[ 2. -2.]
 [ 3. -2.]]
[[-0.8 -2.4]
 [-1.1 -3.3]]


In [251]:
import json
import numpy
import pandas as pd
    
def single_type_candy_count(filename):
  
    out = 0

    with open(filename) as f:
        data = json.load(f)
        for pkmn in data["pokemon"]:
            if (len(pkmn["type"]) == 1):
                if ('candy_count' in pkmn):
                    out = out + pkmn["candy_count"]
        
    return out
    
single_type_candy_count("pokedex.json")

2712

In [18]:
import json
import csv
import numpy as np
import pandas as pd

def histogram_times(filename):

    out = []
    
    flight_data = pd.read_csv(filename)
    flight_data1 = flight_data.dropna(subset = ['Time'])
    flight_data1['Time'] = flight_data1['Time'].str.split(':').str[0]

    #Removing the bad values
    flight_data1 = flight_data1.drop(flight_data1.index[flight_data1.Time == 'c'])
    flight_data1 = flight_data1.drop(flight_data1.index[flight_data1.Time == 'c16'])
    flight_data1 = flight_data1.drop(flight_data1.index[flight_data1.Time == 'c14'])
    flight_data1 = flight_data1.drop(flight_data1.index[flight_data1.Time == '114'])
    flight_data1 = flight_data1.drop(flight_data1.index[flight_data1.Time == '0943'])
    flight_data1 = flight_data1.drop(flight_data1.index[flight_data1.Time == '18.40'])
    flight_data1 = flight_data1.drop(flight_data1.index[flight_data1.Time == '22\'08'])
    flight_data1 = flight_data1.drop(flight_data1.index[flight_data1.Time == '12\'20'])

    #Convert into a series and also into ints
    flight_data2 = pd.Series(flight_data1['Time'])
    flight_data2.sort_values(ascending = True)
    flight_data2 = pd.to_numeric(flight_data2, errors='coerce')

    #Counter for the value 
    flight_data3 = flight_data2.value_counts(normalize=False, sort=True, ascending=False, bins=None, dropna=True)
    
    for x in range (len(flight_data3)):
        out.append(flight_data3[x])

   
    return out

print(histogram_times("airplane_crashes.csv"))

[63, 66, 79, 49, 65, 60, 85, 132, 141, 183, 167, 171, 165, 157, 166, 171, 156, 155, 146, 181, 154, 108, 105, 111]


/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':


In [25]:

import numpy as np
import pandas as pd
import math

def sigmoid_normalize(image, a):
    
    for x in range(len(image)):
        for y in range(len(image[0])):
            p = image[x,y]
            image[x,y] = 255 * ((255 * (1 + math.exp( (p-128) * ((-a) ** (-1)) )))**(-1)) 
    
    return image


print(sigmoid_normalize(np.array([[2.0,2.0], [3.0,2.0]]), 2))










			#image[x,y] = 255 * ((255 * (1 + math.exp( (p-128) * ((-a) ** (-1)) )))**(-1)) 
   




[[4.35961000e-28 4.35961000e-28]
 [7.18778174e-28 4.35961000e-28]]
